spring:
  application:
    name: rest-with-spring-boot-and-java-erudio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/taskdb?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html